### ISSUE TITLE
MacOS daemon not starting with v2.0.2.1 

### ISSUE THREAD

**Issue by jannheider** [valiant1x/intensecoinwallet#50] opened 2018-05-25 14:06 UTC
Downloadet Wallet and startet Wallet... It waits for daemon start but after a wile you get "Daemon could not be startet"

If you go to the shell and try something like this: 
`/Applications/intensecoin-wallet-gui.pp/Contents/MacOS/intensecoind --help`

you get:
```
dyld: Library not loaded: /usr/local/opt/boost/lib/libboost_chrono-mt.dylib
  Referenced from: /Applications/intensecoin-wallet-gui.app/Contents/MacOS/./intensecoind
  Reason: image not found
Abort trap: 6
```

MacOS 10.12.6

**Comment by iedemam** [comment] 2018-05-25 14:28
Thanks for the details. That's enough info to see the obvious problem.

**Comment by tonyxia2016** [comment] 2018-06-04 07:33
I got the exact same issue at first.

After running "brew update && brew upgrade" in the Mac terminal,  the issue is gone. The intensecoind --help is okay, and MacOS v2.0.2.1 GUI runs okay too.
So it should be some boost version issue.

**Comment by jannheider** [comment] 2018-06-04 08:44
@tonyxia2016 

Yes, but this not resolve this issue.
You have installed "Mac Brew" and Boost with Brew (http://brewformulas.org/Boost) which is not a dependency for intensecoinwallet

intensecoinwallet should have libboost static linked.

**Comment by tonyxia2016** [comment] 2018-06-05 07:56
If intensecoinwallet should have libboost static linked, then it compiled it dynamically in this version.

$ otool -l intensecoind |grep boost
         name /usr/local/opt/boost/lib/libboost_chrono-mt.dylib (offset 24)
         name /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (offset 24)
         name /usr/local/opt/boost/lib/libboost_program_options-mt.dylib (offset 24)
         name /usr/local/opt/boost/lib/libboost_regex-mt.dylib (offset 24)
         name /usr/local/opt/boost/lib/libboost_system-mt.dylib (offset 24)
         name /usr/local/opt/boost/lib/libboost_serialization-mt.dylib (offset 24)
         name /usr/local/opt/boost/lib/libboost_date_time-mt.dylib (offset 24)
         name /usr/local/opt/boost/lib/libboost_thread-mt.dylib (offset 24)

Now I have a new issue even after "brew update && brew upgrade", the 1st startup of my MacOS v2.0.2.1 GUI will fail, however the 2nd startup will success.

**Comment by iedemam** [comment] 2018-06-09 09:16
The gui links against libs deployed with the app. The daemon links against system deployed libs. I think we can change the daemon build to use those libs in the app...or, less elegantly, build a static daemon. 

When we build the daemon project, it is built statically. The gui build forces dynamic links because apparently macOS will not allow a mix of static and dynamic links.

Some investigation needed. But, either way, this should be fixed next week.

**gui links**
````
$ otool -L intensecoin-wallet-gui.app/Contents/MacOS/intensecoin-wallet-gui 
intensecoin-wallet-gui.app/Contents/MacOS/intensecoin-wallet-gui:
	@executable_path/../Frameworks/libboost_serialization.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_date_time.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_chrono.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libboost_program_options.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	@executable_path/../Frameworks/QtQuick.framework/Versions/5/QtQuick (compatibility version 5.11.0, current version 5.11.0)
	@executable_path/../Frameworks/QtGui.framework/Versions/5/QtGui (compatibility version 5.11.0, current version 5.11.0)
	@executable_path/../Frameworks/QtCore.framework/Versions/5/QtCore (compatibility version 5.11.0, current version 5.11.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@executable_path/../Frameworks/QtQml.framework/Versions/5/QtQml (compatibility version 5.11.0, current version 5.11.0)
	@executable_path/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.11.0, current version 5.11.0)
	@executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.11.0, current version 5.11.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
````
**daemon links**
````
$ otool -L intensecoin-wallet-gui.app/Contents/MacOS/intensecoind 
intensecoin-wallet-gui.app/Contents/MacOS/intensecoind:
	/usr/local/opt/boost/lib/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_serialization-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/local/opt/boost/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
````

**Comment by qf3l3k** [comment] 2018-06-09 09:19
I did use workaround. Downloaded command line daemon and synchronised with blockchain. Once you run intensecoind in Terminal window and keep it running, start macOS GUI wallet. It will connect properly with intensoind working in Terminal.

**Comment by iedemam** [comment] 2018-06-12 19:45
New PR here: https://github.com/valiant1x/intensecoinwallet/pull/56
And test build here: https://we.tl/1VZiEkSqZv

Let me know if that macOS build fixes the issue. Thanks!

**Comment by iedemam** [comment] 2018-06-15 10:28
official build updated

**Closed by iedemam** 2018-06-15 10:28 UTC
